Add pitch_string_analysis
SuibianP/utau-zh-docs pull request #3
Opened 2022-05-12 06:09 UTC by ookamitai

Added pitch_string_analysis :DDD

2022-05-14 14:21 UTC, SuibianP reviewed
Thanks a lot for the efforts!

The visualisation might be better generated as a vector image, which scales and versions more easily.

I do not currently have an available MkDocs installation at hand to verify (not willing to breach company policies). Could you please kindly enable GitHub Pages from your repository and trigger the GitHub Action workflow so that the effects can be seen from https://ookamitai.github.io/utau-zh-docs/?

As a side comment, did you mean to commit to the `add_pitch_decode` branch in your fork instead?

2022-05-16 11:42 UTC, SuibianP requested changes
Please append to [CONTRIBUTORS.md](https://github.com/ookamitai/utau-zh-docs/blob/doc-source/docs/CONTRIBUTORS.md) as well.

2022-05-16 11:52 UTC, ookamitai commented
Sure thing! However, the .svg file seems that it couldn’t be displayed without certain plugins. Maybe an edit in the .yml may help?

2022-05-16 14:06 UTC, SuibianP commented
Please try using the [Markdown syntax for images](https://daringfireball.net/projects/markdown/syntax#img), which will handle the relative links correctly. You may also want to refer to [this](https://github.com/ookamitai/utau-zh-docs/blob/45bbd616610c9730483383289f7599097ea940c8/docs/docs/%E5%8E%9F%E9%9F%B3%E8%AE%BE%E5%AE%9A1_oto%E6%9D%A1%E7%9B%AE%E5%88%B0%E5%BA%95%E5%8C%85%E5%90%AB%E4%BA%86%E4%BB%80%E4%B9%88/%E5%8E%9F%E9%9F%B3%E8%AE%BE%E5%AE%9A1.md?plain=1#L11).

As can be seen [here](https://github.com/ookamitai/utau-zh-docs/tree/20bf90ce84cc06eca611c52267f12d01c5014a8a/docs/%E5%8E%9F%E9%9F%B3%E8%AE%BE%E5%AE%9A1_oto%E6%9D%A1%E7%9B%AE%E5%88%B0%E5%BA%95%E5%8C%85%E5%90%AB%E4%BA%86%E4%BB%80%E4%B9%88), the Markdown-compiled HTML document actually lives one level down the hierarchy relative to the image.

2022-05-16 14:18 UTC, ookamitai commented
Thanks a lot for your clear explanation! The line has now been replaced with Markdown syntax
:3

2022-05-16 15:02 UTC, SuibianP requested changes
Some lists are currently incorrectly rendered due to missing blank line before it. You may find a (rather lengthy) discussion of this issue [here](https://talk.commonmark.org/t/blank-lines-before-lists-revisited/1990).

Also, thanks for the heads up leading to fix f9a59d19e4242a859592c5c06ffedca5cff06a72!

2022-05-16 16:01 UTC, SuibianP requested changes
There are still several unrectified lists, including line 57, 70 and 85.

2022-05-16 22:44 UTC, ookamitai commented
As I have noticed, some characters are incorrectly highlighted. Any ideas on that?

2022-05-17 02:05 UTC, SuibianP commented
This seems to be due to [`InlineHilite`](https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/#options) inheriting the [`guess_lang` option from `Highlight`](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#options).

Meanwhile, there does not seem to be a viable approach to avoid this behaviour while retaining the ability to highlight individual inline snippets if desired, which I will try to propose upstream. For now, this is fine and not a blocker for this PR.

2022-05-17 02:07 UTC, SuibianP commented on mkdocs.yml
> +
Please also remove this trailing whitespace.

2022-05-17 12:15 UTC, SuibianP approved these changes
LGTM. Thank you very much for your contribution!

2022-05-17 13:41 UTC, ookamitai commented
My pleasure!

2022-05-18 00:55 UTC, merged